Sub Main()
    Dim oDoc As Document
    oDoc = ThisDoc.Document
    oDocName = System.IO.Path.GetDirectoryName(oDoc.FullFileName) & "\" & System.IO.Path.GetFileNameWithoutExtension(oDoc.FullFileName)
    
    If Not (oDoc.DocumentType = kAssemblyDocumentObject Or oDoc.DocumentType = kDrawingDocumentObject) Then
        MessageBox.Show("Please run this rule from the assembly or drawing files.", "iLogic")
        Exit Sub
    End If
    
    'get user input
    If MessageBox.Show ( _
        "This will Print all of the files referenced by this document that have drawings files." _
        & vbLf & "This rule expects that the drawing file shares the same name and location as the component." _
        & vbLf & " " _
        & vbLf & "Are you sure you want to Print Drawings for all of the referenced documents?" _
        & vbLf & "This could take a while.", "iLogic  - Batch Output PDFs ",MessageBoxButtons.YesNo) = vbNo Then
        Exit Sub
    End If
        
    
    '- - - - - - - - - - - - -Component Drawings - - - - - - - - - - - -
    Dim oRefDoc As Document
    Dim oDrawDoc As DrawingDocument
    
    For Each oRefDoc In oDoc.AllReferencedDocuments
        oBaseName = System.IO.Path.GetFileNameWithoutExtension(oRefDoc.FullFileName)
        oPathAndName = System.IO.Path.GetDirectoryName(oRefDoc.FullFileName) & "\" & oBaseName
        If(System.IO.File.Exists(oPathAndName & ".idw")) Then
            oDrawDoc = ThisApplication.Documents.Open(oPathAndName & ".idw", True)
			InventorVb.DocumentUpdate()
			'Print Setup
			Dim oDrgDoc As DrawingDocument
			oDrgDoc = ThisApplication.ActiveDocument
			Dim oDrgPrintMgr As DrawingPrintManager
			oDrgPrintMgr = oDrgDoc.PrintManager
			oDrgPrintMgr.Printer = "\\server03\Drawing Printer"
			oDrgPrintMgr.ScaleMode = kPrintBestFitScale
			oDrgPrintMgr.PaperSize = kPaperSizeA4
			oDrgPrintMgr.PrintRange = kPrintAllSheets
			oDrgPrintMgr.AllColorsAsBlack = False
			oDrgPrintMgr.RemoveLineWeights = False
			oDrgPrintMgr.Rotate90Degrees = False
			oDrgPrintMgr.TilingEnabled = False
			oDrgPrintMgr.Orientation = kLandscapeOrientation
			oDrgPrintMgr.SubmitPrint
			oDrawDoc.Close
        Else
            oNoDwgString = oNoDwgString & vbLf & idwPathName
        End If
    Next
    
    '- - - - - - - - - - - - -Top Level Drawing - - - - - - - - - - - -
    oBaseName = System.IO.Path.GetFileNameWithoutExtension(oDoc.FullFileName)
    oPathAndName = System.IO.Path.GetDirectoryName(oDoc.FullFileName) & "\" & oBaseName
    
    If oDoc.DocumentType = kAssemblyDocumentObject Then
        oDrawDoc = ThisApplication.Documents.Open(oPathAndName & ".idw", True)
		InventorVb.DocumentUpdate()
	    'Print Setup		
		Dim oDrgDoc As DrawingDocument
		oDrgDoc = ThisApplication.ActiveDocument
		Dim oDrgPrintMgr As DrawingPrintManager
		oDrgPrintMgr = oDrgDoc.PrintManager
		oDrgPrintMgr.Printer = "\\server03\Drawing Printer"
		oDrgPrintMgr.ScaleMode = kPrintBestFitScale
		oDrgPrintMgr.PaperSize = kPaperSizeA4
		oDrgPrintMgr.PrintRange = kPrintAllSheets
		oDrgPrintMgr.AllColorsAsBlack = False
		oDrgPrintMgr.RemoveLineWeights = False
		oDrgPrintMgr.Rotate90Degrees = False
		oDrgPrintMgr.TilingEnabled = False
		oDrgPrintMgr.Orientation = kLandscapeOrientation
		oDrgPrintMgr.SubmitPrint
		oDrawDoc.Close
		
    ElseIf oDoc.DocumentType = kDrawingDocumentObject Then
		    'Print Setup
			Dim oDrgDoc As DrawingDocument
			oDrgDoc = ThisApplication.ActiveDocument
			Dim oDrgPrintMgr As DrawingPrintManager
			oDrgPrintMgr = oDrgDoc.PrintManager
			oDrgPrintMgr.Printer = "\\server03\Drawing Printer"
			oDrgPrintMgr.ScaleMode = kPrintBestFitScale
			oDrgPrintMgr.PaperSize = kPaperSizeA4
			oDrgPrintMgr.PrintRange = kPrintAllSheets
			oDrgPrintMgr.AllColorsAsBlack = False
			oDrgPrintMgr.RemoveLineWeights = False
			oDrgPrintMgr.Rotate90Degrees = False
			oDrgPrintMgr.TilingEnabled = False
			oDrgPrintMgr.Orientation = kLandscapeOrientation
			oDrgPrintMgr.SubmitPrint
			oDrawDoc.Close
    End If
    
    MsgBox("Files found without drawings: " & vbLf & oNoDwgString)
End Sub
